default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_educa_somar_development

test:
  <<: *default
  database: api_educa_somar_test

production:
  <<: *default
  database: api_educa_somar_production
  username: api_educa_somar
  password: <%= ENV['API_EDUCA_SOMAR_DATABASE_PASSWORD'] %>
